---
- hosts: localhost
  connection: local
  become: root
  vars:
   image: centos:7
   container_name: jupyter_container
   image_name: jupyterlab
  tasks:
  - name: Make image available
    docker_image:
      name: '{{ image }}'
  - name: Create container
    docker_container:
      image: '{{ image }}'
      name: '{{ container_name }}'
      command: sleep infinity
